---
#
# install docker
#
- hosts: k8s-single
  roles:
    - docker
    - kube-deps 

#
# master init
#
- hosts: k8s-master
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes

    - name: install Pod network
#      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

#
# master traint
#
- hosts: k8s-master
  tasks:
    - name: initialize the cluster
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-

