---
- name: Install Docker
  yum: name=docker state=present update_cache=yes
  tags:
    - docker

- name: Install docker-compose
  get_url: url=https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64  dest=/usr/local/bin/docker-compose mode='0755'
  tags:
    - docker

- name: Start Docker Service
  service: name=docker state=started enabled=yes
  tags:
    - docker

