---

galaxy_info:
  author: <authors_name>
  description: <description>
  license: <license_name>
  min_ansible_version: 1.7
  platforms:
    - name: <platform>
      versions:
        - <platform_version>
  categories:
    - system
dependencies: []
