---
#
# 支持两个变量：droplets、do_token
#
- name: ensure key exists at DigitalOcean
  digital_ocean: >
    state=present
    command=ssh
    name=yfb-pub
    ssh_pub_key={{ lookup('file', 'ssh_keys/yfb.pub') }}
    api_token={{ do_token }}
  register: do_ssh_key

- debug: msg="do_ssh_key is {{ do_ssh_key }}"

- name: ensure droplet exists
  digital_ocean: >
    state=present
    command=droplet
    name={{ item }}
    size_id={{ do_size_id }}
    region_id=nyc1
    image_id=centos-7-x64
    ssh_key_ids={{ do_ssh_key.ssh_key.id }}
    unique_name=yes
    api_token={{ do_token }}
  with_items: "{{ droplets }}"
  register: droplet_details

- debug: msg="IP is {{ item.droplet.ip_address }}"
  with_items: "{{ droplet_details.results }}"

